apiVersion: v1
entries:
  n8n:
  - apiVersion: v2
    appVersion: 1.117.3
    created: "2025-11-03T10:26:14.350230523+07:00"
    description: A Helm chart for n8n workflow automation with separate webhook service
    digest: 31c0833cbb65b2c22eca4af8adf3a61926aebc527ea55fe3c57e9ae11846fde8
    home: https://n8n.io
    keywords:
    - n8n
    - workflow
    - automation
    - webhook
    maintainers:
    - name: hieudc
    name: n8n
    sources:
    - https://github.com/n8n-io/n8n
    type: application
    urls:
    - https://docaohieu2808.github.io/n8n-helm-charts/charts/n8n-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-03T10:26:14.349204031+07:00"
