apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.main.replicaCount }}
  selector:
    matchLabels:
      app: n8n-main
  template:
    metadata:
      labels:
        app: n8n-main
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - n8n-main
              topologyKey: kubernetes.io/hostname
      containers:
      - name: n8n-main
        image: {{ .Values.main.image.repository }}:{{ .Values.main.image.tag }}
        imagePullPolicy: {{ .Values.main.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.main.service.targetPort }}
        command: ["n8n"]
        args: ["start"]
        env:
        - name: N8N_HOST
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_HOST
        - name: N8N_PORT
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_PORT
        - name: N8N_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_PROTOCOL
        - name: WEBHOOK_URL
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: WEBHOOK_URL
        - name: GENERIC_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: GENERIC_TIMEZONE
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_TYPE
        - name: DB_POSTGRESDB_HOST
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_HOST
        - name: DB_POSTGRESDB_PORT
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_PORT
        - name: DB_POSTGRESDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_DATABASE
        - name: DB_POSTGRESDB_USER
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_USER
        - name: DB_POSTGRESDB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_SCHEMA
        - name: DB_POSTGRESDB_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_POOL_SIZE
        - name: DB_POSTGRESDB_MIN_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_MIN_POOL_SIZE
        - name: DB_POSTGRESDB_ACQUIRE_TIMEOUT_MILLIS
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_ACQUIRE_TIMEOUT_MILLIS
        - name: DB_POSTGRESDB_CONNECTION_TIMEOUT_MILLIS
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_CONNECTION_TIMEOUT_MILLIS
        - name: DB_POSTGRESDB_IDLE_TIMEOUT_MILLIS
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_IDLE_TIMEOUT_MILLIS
        - name: DB_POSTGRESDB_MAX_USES
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_MAX_USES
        - name: DB_POSTGRESDB_SSL_ENABLED
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_SSL_ENABLED
        - name: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: POSTGRES_PASSWORD
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: N8N_ENCRYPTION_KEY
        - name: EXECUTIONS_MODE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: EXECUTIONS_MODE
        - name: QUEUE_BULL_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: QUEUE_BULL_REDIS_HOST
        - name: QUEUE_BULL_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: QUEUE_BULL_REDIS_PORT
        - name: QUEUE_BULL_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: REDIS_PASSWORD
        - name: QUEUE_BULL_REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: QUEUE_BULL_REDIS_DB
        - name: EXECUTIONS_DATA_SAVE_ON_ERROR
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: EXECUTIONS_DATA_SAVE_ON_ERROR
        - name: EXECUTIONS_DATA_SAVE_ON_SUCCESS
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        - name: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        - name: EXECUTIONS_DATA_PRUNE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: EXECUTIONS_DATA_PRUNE
        - name: EXECUTIONS_DATA_MAX_AGE
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: EXECUTIONS_DATA_MAX_AGE
        - name: N8N_METRICS
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_METRICS
        - name: N8N_CONCURRENCY_PRODUCTION_LIMIT
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_CONCURRENCY_PRODUCTION_LIMIT
        - name: N8N_TRUST_PROXY
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_TRUST_PROXY
        - name: N8N_CACHE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_CACHE_ENABLED
        - name: N8N_USER_MANAGEMENT_JWT_SECRET_CACHE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: N8N_USER_MANAGEMENT_JWT_SECRET_CACHE_ENABLED
        - name: CACHE_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: CACHE_REDIS_HOST
        - name: CACHE_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: CACHE_REDIS_PORT
        - name: CACHE_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: REDIS_PASSWORD
        - name: CACHE_REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: CACHE_REDIS_DB
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              name: n8n-config
              key: NODE_TLS_REJECT_UNAUTHORIZED
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: n8n-main-files
          mountPath: /home/node/.n8n
        {{- end }}
        resources:
          {{- toYaml .Values.main.resources | nindent 10 }}
        startupProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.main.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.main.service.targetPort }}
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.main.service.targetPort }}
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: n8n-main-files
        persistentVolumeClaim:
          claimName: n8n-main-pvc
      {{- end }}
