apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  N8N_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  REDIS_ENCRYPTION_KEY: {{ .Values.secrets.redisEncryptionKey | quote }}
